### PR TITLE
Fix of FEA unit test with tolerance for permutation-based scores

### LINKED ISSUE #163: Fix unit testing data mismatch for FEA function with fgsea method

### PR DESCRIPTION
**Pull request by AlessiaCampo**
Fix #163 
The PR contains fixes in how the ranked list of genes is ordered in case of tie values before performing fgsea. In this case the sorting is performed alphabetically. This would avoid to get random ordering of the genes before fgsea is performed. 

The test-that for FEA has been fixed for the unit test of fgsea to check the exact equality of the pathway names and size columns. 
For the ES score columns a strict tolerance value is used to check equality, whereas for NES, p.value and adjusted p.value a looser tolerance is used since all these scores are permutation-based.

### CODE REVIEW

File: R/FEA.R [hunk 1]
```diff
@@ -19,7 +20,8 @@
 #' dataFEA <- FEA(DiffMatrix = DEGsmatrix, BPname = "apoptosis")
 FEA <- function(BPname = NULL,
                 DiffMatrix,
-                method = "ora") {
+                method = "ora",
+                seed = 123) {
```
Comment (mtiberti) [inline R/FEA.R]: can we set this to `NULL` by default?

the idea being, we don't set the seed unless explicitly asked to

File: R/FEA.R [hunk 2]
```diff
@@ -82,7 +86,8 @@ FEA <- function(BPname = NULL,
 
     pathway_sizes <- sapply(DiseaseList, function(pathway) length(unique(pathway$ID)))
     max_pathway_size <- max(pathway_sizes)
-
+    
+    set.seed(seed)
```
Comment (mtiberti) [inline R/FEA.R]: can this be conditional to `seed` not being `NULL`?

File: tests/testthat/test-FEA.R [hunk 3]
```diff
@@ -6,7 +6,6 @@ data("DiseaseList")
 data("EAGenes")
 DEGsmatrix_ora <- DEGsmatrix[1:10, ]
 dataFEA_test_ora <- FEA(DiffMatrix = DEGsmatrix_ora, method="ora")
-set.seed(123)
 dataFEA_test_fgsea <- FEA(DiffMatrix = DEGsmatrix, method="fgsea")
```
Comment (mtiberti) [inline tests/testthat/test-FEA.R]: of course with the change I am proposing we will need to change seed

File: R/FEA.R [hunk 4]
```diff
@@ -7,6 +7,7 @@
 #' @param BPname BPname biological process such as "proliferation of cells", "ALL" (default) if FEA should be carried out for all 101 biological processes
 #' @param DiffMatrix output from DEA such as dataDEGs or from DAA such as differential abundace matrix
 #' @param method method to perform Functional Enirchment analysis. Must be either "ora" (Over-Representation Analysis) or "fgsea" (Fast Gene Set Enrichment Analysis)
+#' @param seed internal seed before the 'fgsea' function is called to ensure reproducibility of the permutation-based p-values. Default is 123
```
Comment (mtiberti) [inline R/FEA.R]: to be changed (see below)

File: NEWS.md [hunk 5]
```diff
@@ -1,3 +1,9 @@
+# Moonlight2R 1.9.3
+
+## Summary
+
+* Fixed tests for FEA with "fgsea" as method
```
Comment (mtiberti) [inline NEWS.md]: and added new argument to FEA...

**Review by mtiberti — CHANGES_REQUESTED** [review]

**Review by mtiberti — APPROVED** [review]
